name: CI
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: xcodebuild clean test -project SwiftyKeychainKit.xcodeproj -scheme SwiftyKeychainKit -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0.1' | xcpretty